"""Whatsapp domain: the Payment Proposal lifecycle and the webhook signature check.

Map: `payment_proposal` (Proposta de Lançamento — state, staging key, message/
button/list formatting; not a fact until confirmed), `signature` (HMAC-SHA256
verification of the Meta webhook, pure). Grows module-per-concept (ADR-0015).
"""

from luc_api.whatsapp.domain.payment_proposal import (
    ACTION_CANCEL,
    ACTION_CHANGE,
    ACTION_CONFIRM,
    ACTION_SWAP,
    ACTIVE_PROPOSAL_STATES,
    CHANGE_MENU_TITLE,
    CHOOSE_BILL_PREFIX,
    CHOOSE_FIELD_PREFIX,
    CHOOSE_MONTH_PREFIX,
    FREE_TEXT_FIELDS,
    MONTH_LIST_TITLE,
    PROPOSAL_TTL_DAYS,
    BillOption,
    ChangeAction,
    ChooseBillAction,
    ChooseFieldAction,
    ChooseMonthAction,
    ConfirmOrCancelAction,
    EditableField,
    FreeTextField,
    InteractiveButton,
    InteractiveRow,
    NewPaymentProposal,
    PaymentProposal,
    PaymentProposalData,
    ProposalAction,
    ProposalState,
    ProposalSummary,
    bill_rows,
    describe_month_in_full,
    duplicate_receipt_message,
    expired_proposal_message,
    field_edit_prompt,
    field_not_understood_message,
    field_rows,
    format_payment_created,
    format_proposal_message,
    is_expired,
    is_free_text_field,
    parse_button_action,
    proposal_buttons,
    receipt_hash,
    reference_period_rows,
    staging_key_for,
)
from luc_api.whatsapp.domain.signature import signature_valid

__all__ = [
    "ACTION_CANCEL",
    "ACTION_CHANGE",
    "ACTION_CONFIRM",
    "ACTION_SWAP",
    "ACTIVE_PROPOSAL_STATES",
    "CHANGE_MENU_TITLE",
    "CHOOSE_BILL_PREFIX",
    "CHOOSE_FIELD_PREFIX",
    "CHOOSE_MONTH_PREFIX",
    "FREE_TEXT_FIELDS",
    "MONTH_LIST_TITLE",
    "PROPOSAL_TTL_DAYS",
    "BillOption",
    "ChangeAction",
    "ChooseBillAction",
    "ChooseFieldAction",
    "ChooseMonthAction",
    "ConfirmOrCancelAction",
    "EditableField",
    "FreeTextField",
    "InteractiveButton",
    "InteractiveRow",
    "NewPaymentProposal",
    "PaymentProposal",
    "PaymentProposalData",
    "ProposalAction",
    "ProposalState",
    "ProposalSummary",
    "bill_rows",
    "describe_month_in_full",
    "duplicate_receipt_message",
    "expired_proposal_message",
    "field_edit_prompt",
    "field_not_understood_message",
    "field_rows",
    "format_payment_created",
    "format_proposal_message",
    "is_expired",
    "is_free_text_field",
    "parse_button_action",
    "proposal_buttons",
    "receipt_hash",
    "reference_period_rows",
    "signature_valid",
    "staging_key_for",
]
